api:
  type: completion
  streaming: true
  headers: null
data:
  type: synthetic
  path: null
  input_distribution:
    min: 10
    max: 100
    mean: 50.0
    std_dev: 200.0
    total_count: 61
  output_distribution:
    min: 10
    max: 100
    mean: 50.0
    std_dev: 200.0
    total_count: 61
  shared_prefix: null
  trace: null
load:
  type: constant
  interval: 15.0
  stages:
  - rate: 1.0
    duration: 30
    num_requests: null
    concurrency_level: null
  - rate: 2.0
    duration: 30
    num_requests: null
    concurrency_level: null
  sweep: null
  num_workers: 16
  worker_max_concurrency: 100
  worker_max_tcp_connections: 2500
  trace: null
  circuit_breakers: []
  request_timeout: null
metrics:
  type: prometheus
  prometheus:
    scrape_interval: 15
    url: http://localhost:9090/
    filters: []
    google_managed: false
report:
  request_lifecycle:
    summary: true
    per_stage: true
    per_request: true
    percentiles:
    - 0.1
    - 1.0
    - 5.0
    - 10.0
    - 25.0
    - 50.0
    - 75.0
    - 90.0
    - 95.0
    - 99.0
    - 99.9
  prometheus:
    summary: true
    per_stage: false
storage:
  local_storage:
    path: reports-20260511-112709
    report_file_prefix: null
  google_cloud_storage: null
  simple_storage_service: null
server:
  type: vllm
  model_name: meta-llama/Llama-3.1-8B-Instruct
  base_url: http://0.0.0.0:8000
  ignore_eos: true
  api_key: null
  cert_path: null
  key_path: null
tokenizer:
  pretrained_model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
  trust_remote_code: null
  token: null
circuit_breakers: null
